---
services:
  db:
    image: surrealdb/surrealdb
    ports:
      - 8000:8000
    env_file: .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD

volumes:
  dbdata: {}
